{
 "title": "Validator Info",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "###### Cosmos_Network ######", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{chainId}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_blockHeight{instance=\"localhost:26661\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_proposerWalletAccountNumber{instance=\"localhost:26661\"}",
     "legendFormat": "proposerWalletAccountNumber"
    }
   ]
  },
  {
   "title": "[ Current Block Time ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "Cosmos_currentBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "currentBlockTime"
    },
    {
     "expr": "Cosmos_defaultBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "defaultBlockTime"
    }
   ]
  },
  {
   "title": "[ Token Info ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(Cosmos_notBondedTokens{instance=\"localhost:26661\"}+Cosmos_bondedTokens{instance=\"localhost:26661\"})",
     "legendFormat": "totalTokens"
    },
    {
     "expr": "round(Cosmos_bondedTokens{instance=\"localhost:26661\"})",
     "legendFormat": "bondedTokens"
    },
    {
     "expr": "round(Cosmos_notBondedTokens{instance=\"localhost:26661\"})",
     "legendFormat": "notBondedTokens"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_bondedRate{instance=\"localhost:26661\"}*100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_validatorCount{instance=\"localhost:26661\"}"
    }
   ]
  },
  {
   "title": "[ Block Precommit Rate(%) ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Cosmos_precommitRate{instance=\"localhost:26661\"}",
     "legendFormat": "commitStatus"
    }
   ]
  },
  {
   "title": "[ Blocks Per Year]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_blocksPerYear{instance=\"localhost:26661\"}\t",
     "legendFormat": "blocksPerYear"
    }
   ]
  },
  {
   "title": "[ Default Block Time ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_defaultBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "currentBlockTime"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_inflationMin{instance=\"localhost:26661\"}*100",
     "legendFormat": "inflationMin"
    }
   ]
  },
  {
   "title": "[ Inflation_Default Block Time ]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_defaultBlockTimeInflation{instance=\"localhost:26661\"}*100",
     "legendFormat": "defaultBlockTimeInflation"
    }
   ]
  },
  {
   "title": "[ Inflation History ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Inflation_Default Block Time" }
   ],
   "targets": [
    {
     "expr": "Cosmos_defaultBlockTimeInflation{instance=\"localhost:26661\"}*100",
     "legendFormat": "Inflation_Default Block Time"
    },
    {
     "expr": "Cosmos_currentBlockTimeInflation{instance=\"localhost:26661\"}*100",
     "legendFormat": "Inflation_Cureent Block Time"
    }
   ]
  },
  {
   "title": "[ Current Block Time ]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_currentBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "currentBlockTime"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_inflationMax{instance=\"localhost:26661\"}*100",
     "legendFormat": "inflationMax"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_inflationGoalBonded{instance=\"localhost:26661\"}*100",
     "legendFormat": "inflationGoalBonded"
    }
   ]
  },
  {
   "title": "[ Inflation_Current Block Time ]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_currentBlockTimeInflation{instance=\"localhost:26661\"}*100",
     "legendFormat": "currentBlockTimeInflation"
    }
   ]
  },
  {
   "title": "[ Average Block Time ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Cosmos_currentBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "currentBlockTime"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_inflationRateChange{instance=\"localhost:26661\"}*100",
     "legendFormat": "inflationRateChange"
    }
   ]
  },
  { "title": "###### Cosmos_Validator ######", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "[ Operator-Address ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{operatorAddress}}"
    }
   ]
  },
  {
   "title": "[ Account-Address ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{accountAddress}}"
    }
   ]
  },
  {
   "title": "[ Account-Address ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 22 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{accountAddress}}"
    }
   ]
  },
  {
   "title": "[ Consensus-PublicKey ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 22 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{validatorPubKey}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 24 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_votingPower{instance=\"localhost:26661\"}",
     "legendFormat": "votingPower"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 24 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_delegationRatio{instance=\"localhost:26661\"}*100",
     "legendFormat": "delegationRatio"
    }
   ]
  },
  {
   "title": "[ Commission-Rate ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 24 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_commissionRate{instance=\"localhost:26661\"}*100",
     "legendFormat": "commissionRate"
    }
   ]
  },
  {
   "title": "[ Proposing Priority ]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "Cosmos_proposerPriority{instance=\"localhost:26661\"}",
     "legendFormat": "jailStatus"
    }
   ]
  },
  {
   "title": "[ Jail Status ]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
   "targets": [
    {
     "expr": "Cosmos_jailed{instance=\"localhost:26661\"}\t",
     "legendFormat": "jailStatus"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 26 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_selfDelegationAmount{instance=\"localhost:26661\"}\t",
     "legendFormat": "selfDelegationAmount"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 26 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_delegatorCount{instance=\"localhost:26661\"}",
     "legendFormat": "delegatorCount"
    }
   ]
  },
  {
   "title": "[ Commission-MaxChangeRate ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_commissionMaxChangeRate{instance=\"localhost:26661\"}*100",
     "legendFormat": "commissionMaxChangeRate"
    }
   ]
  },
  {
   "title": "[ Self Delegation Amount(Luna) History ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Cosmos_selfDelegationAmount{instance=\"localhost:26661\"}",
     "legendFormat": "selfDelegationAmount"
    }
   ]
  },
  {
   "title": "[ Proposing Status ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Cosmos_proposingStatus{instance=\"localhost:26661\"}",
     "legendFormat": "proposingStatus"
    }
   ]
  },
  {
   "title": "[ Commission-MaxRate ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 30 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Cosmos_commissionMaxRate{instance=\"localhost:26661\"}*100",
     "legendFormat": "commissionMaxRate"
    }
   ]
  },
  {
   "title": "[ Precommit Status(Uptime) ]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Cosmos_validatorCommitStatus{instance=\"localhost:26661\"}",
     "legendFormat": "validatorCommitStatus"
    }
   ]
  },
  {
   "title": "[ Current Balances+Rewards ]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "Cosmos_balances_uatom{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "balaces"
    },
    {
     "expr": "Cosmos_commission_uatom{instance=\"localhost:26661\"}",
     "legendFormat": "commission"
    },
    {
     "expr": "Cosmos_rewards_uatom{instance=\"localhost:26661\"}",
     "legendFormat": "rewards"
    }
   ]
  },
  {
   "title": "[ Balances+Rewards History ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Cosmos_balances_uatom{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "balances"
    },
    {
     "expr": "Cosmos_commission_uatom{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "commission"
    },
    {
     "expr": "Cosmos_rewards_uatom{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "rewards"
    }
   ]
  },
  {
   "title": "[ Balances+Rewards DataTable ]",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 37 },
   "targets": [
    {
     "expr": "Cosmos_balances_uatom{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "balances"
    },
    {
     "expr": "Cosmos_commission_uatom{instance=\"localhost:26661\"}\n",
     "legendFormat": "commission"
    },
    {
     "expr": "Cosmos_rewards_uatom{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "rewards"
    }
   ]
  }
 ]
}